sudo: required

language:
 - c

compiler:
  - gcc

sudo: false
addons:
  apt:
    packages:
    - build-essential
    - fxload
    - gnupg
    - libftdi-dev
    - libreadline-dev
    - libusb-1.0-0-dev
    - python-yaml
    - realpath

env:
  matrix:
   - ARCH=lm32 BOARD=atlys TARGET=base
   - ARCH=lm32 BOARD=atlys TARGET=hdmi2usb
   - ARCH=lm32 BOARD=atlys TARGET=hdmi2eth
   - ARCH=lm32 BOARD=opsis TARGET=base
   - ARCH=lm32 BOARD=opsis TARGET=hdmi2usb
   - ARCH=lm32 BOARD=pipistrello TARGET=base
   # OpenRISC based soft CPU
   - ARCH=or1k BOARD=pipistrello TARGET=base
   - ARCH=or1k BOARD=atlys TARGET=base
   - ARCH=or1k BOARD=opsis TARGET=base

install:
 - $PWD/.travis/setup.sh

script:
 - $PWD/.travis/run.sh

notifications:
 email:
  - hdmi2usb-spam@googlegroups.com
 irc:
  channels:
   - "chat.freenode.net#hdmi2usb"
  template:
   - "[%{repository_slug}/%{branch}#%{build_number}] (%{commit}): %{message} (%{build_url})"
