language:
 - c

compiler:
  - gcc

sudo: false
addons:
  apt:
    packages:
    - build-essential
    - fxload
    - gnupg
    - libftdi-dev
    - libreadline-dev
    - libusb-1.0-0-dev
    - python-yaml
    - realpath
    - util-linux

git:
  submodules: false

env:
  global:
   - HDMI2USB_UDEV_IGNORE=1
   - CLEAN_CHECK=1
   # Travis reports incorrect the hosts number of processors, override to 2
   # cores.
   - JOBS=2

install:
 - export CPU="$C"
 - export PLATFORMS="$P"
 - export TARGETS="$T"
 - $PWD/.travis/setup.sh

script:
 - $PWD/.travis/build.sh

notifications:
 email:
  - hdmi2usb-spam@googlegroups.com
 irc:
  channels:
   - "chat.freenode.net#hdmi2usb"
  template:
   - "[%{repository_slug}/%{branch}#%{build_number}] (%{commit}): %{message} (%{build_url})"

jobs:
  fail_fast: true
  allow_failures:
  - env: C=or1k P=mimasv2      T="base"

  include:
  #--------------------------------------------
  # Base targets
  #--------------------------------------------
  # lm32 Base targets
  - stage: Targets - Base
    env: C=lm32 P=arty         T="base net"

  - stage: Targets - Base
    env: C=lm32 P=atlys        T="base net"

  - stage: Targets - Base
    env: C=lm32 P=mimasv2      T="base"

  - stage: Targets - Base
    env: C=lm32 P=minispartan6 T="base"

  - stage: Targets - Base
    env: C=lm32 P=netv2        T="base"

  - stage: Targets - Base
    env: C=lm32 P=nexys_video  T="base net"

  - stage: Targets - Base
    env: C=lm32 P=opsis        T="base net"

  - stage: Targets - Base
    env: C=lm32 P=pipistrello  T="base"

  # or1k base targets
  - stage: Targets - Base
    env: C=or1k P=arty         T="base net"

  - stage: Targets - Base
    env: C=or1k P=atlys        T="base net"

  - stage: Targets - Base
    env: C=or1k P=mimasv2      T="base"

  - stage: Targets - Base
    env: C=or1k P=opsis        T="base net"

  - stage: Targets - Base
    env: C=or1k P=pipistrello  T="base"

  #--------------------------------------------
  # Video Targets
  #--------------------------------------------
  - stage: Targets - Video
    env: C=lm32 P=atlys        T="video"

  - stage: Targets - Video
    env: C=lm32 P=netv2        T="video"

  - stage: Targets - Video
    env: C=lm32 P=nexys_video  T="video"

  - stage: Targets - Video
    env: C=lm32 P=opsis        T="video"

  #--------------------------------------------
  # HDMI2USB Targets
  #--------------------------------------------
  - stage: Targets - HDMI2USB
    env: C=lm32 P=atlys T="hdmi2usb"

  - stage: Targets - HDMI2USB
    env: C=lm32 P=opsis T="hdmi2usb"
